version: "2.3"

services:

  # curl $(docker port ngrok 4040)/api/tunnels | grep -Po "https"://[^\"]+
  ngrok:
    container_name: ${PROJECT_NAME}_ngrok
    ports:
      - "0.0.0.0:4040:4040"
    image: wernight/ngrok
    links:
      - "npm"
    environment:
      #- NGROK_AUTH=<>
      #- NGROK_SUBDOMAIN=<>
      - NGROK_REGION=eu
      - NGROK_PORT=npm:3000
      - NGROK_DEBUG=1
      #- NGROK_USERNAME=username
      #- NGROK_PASSWORD=pasword

  npm:
    container_name: ${PROJECT_NAME}_npm
    image: node:7.7.2-alpine
    volumes:
        - ./:/usr/app
    command: 'sh -c "cd /usr/app/ && ./scripts/start.sh"'
