version: "3.6"

services:

  ngrok:
    container_name: ${PROJECT_NAME}_ngrok
    image: wernight/ngrok
    links:
      - "npm"
    environment:
      #- NGROK_AUTH=<>
      #- NGROK_SUBDOMAIN=<>
      - NGROK_REGION=eu
      - NGROK_PORT=npm:3000
      - NGROK_DEBUG=1
      #- NGROK_USERNAME=username
      #- NGROK_PASSWORD=pasword

  npm:
    container_name: ${PROJECT_NAME}_npm
    image: node:7.7.2-alpine
    volumes:
        - ./:/usr/app
    command: 'sh -c "cd /usr/app/ && ./scripts/npm-start.sh"'

  busybox-curl:
    container_name: ${PROJECT_NAME}_busybox_curl
    image: odise/busybox-curl:latest
